config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#top'
  get 'top' => "root#top"
  resources :root
  #root 'post_images#index'
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end
    resources :users, only: [:show, :index, :edit, :update]

    resources :users do
    	member do
    	 get :following, :followers
    	end
    end
    resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :post_image
    attachment :image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :images, dependent: :destroy
	accepts_attachments_for :images, attachment: :image

	validates :title, presence: true
	# validates :image, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships


  attachment :profile_image

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	#before_action :authenticate_user!

	def after_sign_in_path_for(resource)
		post_images_path
	end

	def after_sign_out_path_for(resource)
        top_path # ログアウト後に遷移するpathを設定
    end

	protected

	 def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	 end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.new(post_image_id: post_image.id)
		favorite.save
		redirect_to post_image_path(post_image)
	end

	def destroy
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.find_by(post_image_id: post_image.id)
		favorite.destroy
		redirect_to post_image_path(post_image)
	end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
    before_action :correct_user, only: [:edit, :update, :destroy]
	def new
		@post_image = PostImage.new
        @post_image.images.build
        @user = current_user
        @post_images = @user.post_images
    end

    def create
    	@post_image = PostImage.new(post_image_params)
    	@post_image.user_id = current_user.id
        @user = current_user
        @post_images = @user.post_images
    	if @post_image.save
    	  redirect_to post_images_path
        else
          render :new
        end
    end

    def index
    	@post_images = PostImage.page(params[:page]).reverse_order
        @user = current_user
        @post_images1 = @user.post_images

    end

    def show
    	@post_image = PostImage.find(params[:id])
    	@post_comment = PostComment.new
        @user = current_user
        @post_images = @user.post_images
        @post_comments =  @post_image.post_comments.page(params[:page])
    end

    def edit
        @post_image = PostImage.find(params[:id])
        @user = current_user
        @post_images = @user.post_images
    end

    def update
        @post_image = PostImage.find(params[:id])
        @post_image.update(post_image_params)
        redirect_to post_image_path(@post_image.id)
    end

    def destroy
    	@post_image = PostImage.find(params[:id])
    	@post_image.destroy
        redirect_to post_images_path
    end


    private

    def correct_user
        @post_image = PostImage.find(params[:id])
      if current_user != @post_image.user
         redirect_to post_images_path
      end
    end

    def post_image_params
      	  params.require(:post_image).permit(:title, :body, images_images: [])
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
  	  @user = User.find(params[:id])
  	  @post_images = @user.post_images.page(params[:page]).reverse_order

  end

  def index
      @users = User.page(params[:page]).search(params[:search])
      @user = current_user
      @post_images = @user.post_images
  end

  def edit
  	  @user = User.find(params[:id])
  end

  def update
  	  @user = User.find(params[:id])
  	  @user.update(user_params)
  	  redirect_to user_path(@user.id)
  end

  def following
      @user = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
      @user = User.find(params[:id])
      @users = @user.followers
      render 'show_follower'
  end

  private
  def correct_user
      @user = User.find(params[:id])
    if current_user != @user
       redirect_to users_path
    end
  end

  def user_params
  	  params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def current_user?(user)
		user == current_user
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
<SCRIPT language="JavaScript">
t = 0;
function DspClk() {
  DD = new Date();
  Hours = DD.getHours();
  Minutes = DD.getMinutes();
  Seconds = DD.getSeconds();
  status = Hours + "時" + Minutes + "分" + Seconds +"秒";
  document.ClkForm.Input.value = Hours + "時" + Minutes + "分" + Seconds +"秒";
}
</SCRIPT>
<body>
    <%= yield %>
<footer>
 <div class="container">
  <div class="row">
   <div class="col-xs-3 col-xs-offset-9">
    <p9>CopyRight Sample App</p9>
   </div>
  </div>
 </div>
 </footer>
 </body>
 <script>
  $(document).ready(function(){
   $('.slider').bxSlider();
    });
 </script>
</html>

app/views/template/_header.html.erb
<header>
<div class="container">
 <nav>
  <ul class="nav-list-left">
   <h2>Sample App</h2>
  </ul>
  <ul class="nav-list-right">
   <% if user_signed_in? %>
    <h6><%= link_to "Home", post_images_path, class: "glyphicon glyphicon-home home fa-2x" %>
        <%= link_to "Search", users_path, class: "glyphicon glyphicon-search fa-2x" %>
        <%= link_to 'Mypage', user_path(current_user.id), class: "far fa-user fa-2x" %>
        <%= link_to "Post", new_post_image_path, class: "glyphicon glyphicon-pencil fa-2x" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-in fa-2x" %></h6>
   <% else %>
    <h6><%= link_to "Home", top_path, class: "glyphicon glyphicon-home home fa-2x" %>
        <%= link_to "Log in", new_user_session_path, class: "nav-list-item glyphicon glyphicon-log-in fa-2x" %>
        <%= link_to "Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit fa-2x" %>
        <%= link_to "Sample App", root_index_path, class: "far fa-user fa-2x" %>
    </h6>
   <% end %>
  </ul>
 </nav>
</div>
<nav class="global-nav">
 <ul class="global-nav__list">
  <% if user_signed_in? %>
   <li class="global-nav__item"><%= link_to "Home", post_images_path, class: "glyphicon glyphicon-home home fa-2x" %></li>
   <li class="global-nav__item"><%= link_to "Search", users_path, class: "glyphicon glyphicon-search fa-2x" %></li>
   <li class="global-nav__item"><%= link_to 'Mypage', user_path(current_user.id), class: "far fa-user fa-2x" %></li>
   <li class="global-nav__item"><%= link_to "Post", new_post_image_path, class: "glyphicon glyphicon-pencil fa-2x" %></li>
   <li class="global-nav__item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-in fa-2x" %></li>
  <% else %>
   <li class="global-nav__item"><%= link_to "Home", top_path, class: "glyphicon glyphicon-home home fa-2x" %></li>
   <li class="global-nav__item"><%= link_to "Log in", new_user_session_path, class: "nav-list-item glyphicon glyphicon-log-in fa-2x" %></li>
   <li class="global-nav__item"><%= link_to "Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit fa-2x" %></li>
   <li class="global-nav__item"><%= link_to "Sample App", root_index_path, class: "far fa-user fa-2x" %></li>
  <% end %>
 </ul>
</nav>
<div class="hamburger" id="js-hamburger">
 <span class="hamburger__line hamburger__line--1"></span>
 <span class="hamburger__line hamburger__line--2"></span>
 <span class="hamburger__line hamburger__line--3"></span>
</div>
<div class="black-bg" id="js-black-bg"></div>
</header>