config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#top'
  get 'top' => "root#top"
  resources :root
  #root 'post_images#index'
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end
    resources :users, only: [:show, :index, :edit, :update]

    resources :users do
    	member do
    	 get :following, :followers
    	end
    end
    resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :post_image
    attachment :image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :images, dependent: :destroy
	accepts_attachments_for :images, attachment: :image

	validates :title, presence: true
	# validates :image, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships


  attachment :profile_image

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	#before_action :authenticate_user!

	def after_sign_in_path_for(resource)
		post_images_path
	end

	def after_sign_out_path_for(resource)
        top_path # ログアウト後に遷移するpathを設定
    end

	protected

	 def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	 end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.new(post_image_id: post_image.id)
		favorite.save
		redirect_to post_image_path(post_image)
	end

	def destroy
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.find_by(post_image_id: post_image.id)
		favorite.destroy
		redirect_to post_image_path(post_image)
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
    before_action :correct_user, only: [:destroy]
	def create
		post_image = PostImage.find(params[:post_image_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.post_image_id = post_image.id
		comment.save
		redirect_to post_image_path(post_image)

	end

    def destroy
    	@post_comment = PostComment.find(params[:id])
    	post_image = PostImage.find(params[:post_image_id])
    	@post_comment.destroy
    	redirect_to post_image_path(post_image)
    end

	private

	def correct_user
		post_comment = PostComment.find(params[:id])
		post_image = PostImage.find(params[:post_image_id])
		if current_user != post_comment.user
			redirect_to post_image_path(post_image.id)
		end
	end

	def post_comment_params
		params.require(:post_comment).permit(:user_id, :post_image_id, :comment)
	end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
    before_action :correct_user, only: [:edit, :update, :destroy]
	def new
		@post_image = PostImage.new
        @post_image.images.build
        @user = current_user
        @post_images = @user.post_images
    end

    def create
    	@post_image = PostImage.new(post_image_params)
    	@post_image.user_id = current_user.id
        @user = current_user
        @post_images = @user.post_images
    	if @post_image.save
    	  redirect_to post_images_path
        else
          render :new
        end
    end

    def index
    	@post_images = PostImage.page(params[:page]).reverse_order
        @user = current_user
        @post_images1 = @user.post_images

    end

    def show
    	@post_image = PostImage.find(params[:id])
    	@post_comment = PostComment.new
        @user = current_user
        @post_images = @user.post_images
        @post_comments =  @post_image.post_comments.page(params[:page])
    end

    def edit
        @post_image = PostImage.find(params[:id])
        @user = current_user
        @post_images = @user.post_images
    end

    def update
        @post_image = PostImage.find(params[:id])
        @post_image.update(post_image_params)
        redirect_to post_image_path(@post_image.id)
    end

    def destroy
    	@post_image = PostImage.find(params[:id])
    	@post_image.destroy
        redirect_to post_images_path
    end


    private

    def correct_user
        @post_image = PostImage.find(params[:id])
      if current_user != @post_image.user
         redirect_to post_images_path
      end
    end

    def post_image_params
      	  params.require(:post_image).permit(:title, :body, images_images: [])
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@user = User.find(params[:relationship] [:following_id])
		current_user.follow!(@user)
		redirect_to @user
	end

	def destroy
		@user = Relationship.find(params[:id]).following
		current_user.unfollow!(@user)
		redirect_to @user
	end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
  	  @user = User.find(params[:id])
  	  @post_images = @user.post_images.page(params[:page]).reverse_order

  end

  def index
      @users = User.page(params[:page]).search(params[:search])
      @user = current_user
      @post_images = @user.post_images
  end

  def edit
  	  @user = User.find(params[:id])
  end

  def update
  	  @user = User.find(params[:id])
  	  @user.update(user_params)
  	  redirect_to user_path(@user.id)
  end

  def following
      @user = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
      @user = User.find(params[:id])
      @users = @user.followers
      render 'show_follower'
  end

  private
  def correct_user
      @user = User.find(params[:id])
    if current_user != @user
       redirect_to users_path
    end
  end

  def user_params
  	  params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def current_user?(user)
		user == current_user
	end
end

app/views/post_images/_follow.html.erb
<div class="btn">
 <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <%= f.hidden_field :following_id %>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
 <% end %>
</div>

app/views/post_images/_follow_form.html.erb
<% unless current_user?(@user) %>
 <div id="follow_form">
  <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
  <% else %>
  <%= render 'follow' %>
  <% end %>
 </div>
<% end %>

app/views/post_images/_stats.html.erb
<% @user ||= current_user %>
<h4>
 <div class="follow">
  <%= link_to "#{@user.followings.count}人をフォロー中", following_user_path(@user) %>
  <br>
  <br>
  <%= link_to "フォロワー#{@user.followers.count}人", followers_user_path(@user) %>
 </div>
</h4>

app/views/post_images/edit.html.erb
<%= render 'template/header' %>
<div class="media-area2">
 <div class="container">
  <div class="row">
   <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="circle">
     <h2>User info</h2>
      <table class="table">
       <tbody>
        <div class="image">
         <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class: "img-circle" %>
        </div>
        <br>
         <tr>
          <th>name</th>
          <th><%= @user.name %></th>
         </tr>
        </tbody>
       </table>
       <%= link_to edit_user_path(@user.id) do %>
        <div class="col-xs-12 btn btn-default ">
         <span class="glyphicon glyphicon-wrench" aria-hidden="true" ></span>
        </div>
       <% end %>
       <br>
       <br>
       <h4>投稿<%= @post_images.count %>件</h4>
       <%= render 'follow_form' %>
       <%= render 'stats' %>
    </div>
   </div>
   <div class="col-xs-12 col-md-offset-2 col-md-7">
    <%= form_for(@post_image) do |f| %>
     <div class="slider">
    <% @post_image.images.each do |image| %>
    <%= attachment_image_tag image, :image, size: "500x500", class: "sm-image" %>
    <% end %>
   </div>
   <div class="box3">
    <h4>タイトル</h4>
     <div class="row">
      <div class="col-sm-12">
       <%= f.text_field :title, class: "form-control", warp: "hard" %>
      </div>
     </div>
     <h4>内容</h4>
      <div class="row">
       <div class="col-sm-12">
        <%= f.text_area :body, class: "form-control" %>
       </div>
      </div>
      <br>
      <div class="row">
       <div class="col-sm-12">
        <%= f.submit "更新", class: "btn btn-primary col-xs-12" %>
       </div>
      </div>
        <% end %>
        <br>
        <br>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/post_images/index.html.erb
<%= render 'template/header' %>
<div class="media-area2">
 <div class="container">
  <div class="row">
   <div class="col-xs-12 col-sm-6 col-md-3" >
    <div class="circle">
     <h2>User info</h2>
      <table class="table">
       <tbody>
        <div class="image">
         <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class: "img-circle" %>
        </div>
        <br>
        <tr>
         <th>name</th>
         <th><%= @user.name %></th>
        </tr>
       </tbody>
      </table>
      <%= link_to edit_user_path(@user.id) do %>
      <div class="col-xs-12 btn btn-default ">
       <span class="glyphicon glyphicon-wrench" aria-hidden="true" ></span>
      </div>
      <% end %>
      <br>
      <br>
      <h4>投稿<%= @post_images.count %>件</h4>
      <%= render 'follow_form' %>
      <%= render 'stats' %>
     </div>
    </div>
    <div class="col-xs-12 col-md-offset-2 col-md-7">
     <% @post_images.each do |post_image| %>
      <div class="slider">
       <% post_image.images.each do |image| %>
       <%= attachment_image_tag image, :image, size: "500x500", class: "sm-image" %>
       <% end %>
      </div>
      <div class="box">
       <h3>
        <%= link_to post_image_path(post_image.id) do %>
        <%= post_image.title %>
        <% end %>
       </h3>
       <h3><%= post_image.body %></h3>
       <h4 class="space">
        <%= link_to post_image.user.name, user_path(post_image.user.id) %></h4>
       <h4>コメント<%= post_image.post_comments.count %>件
        いいね<%= post_image.favorites.count %>件
       <%= link_to "コメントをする", post_image_path(post_image.id) %></h4>
       <div class="image2">
        <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60", class: "img-circle profile-thumb" %>
       </div>
       <br>
      </div>
      <hr>
     <% end %>
     <h4><%= paginate @post_images, class: "pagenate" %></h4>
   </div>
  </div>
 </div>
</div>

app/views/post_images/new.html.erb
<%= render 'template/header' %>
<div class="media-area2">
 <div class="container">
  <div class="row">
   <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="circle">
     <h2>User info</h2>
      <table class="table">
       <tbody>
        <div class="image">
         <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class: "img-circle" %>
        </div>
        <br>
        <tr>
         <th>name</th>
         <th><%= @user.name %></th>
        </tr>
       </tbody>
      </table>
      <%= link_to edit_user_path(@user.id) do %>
      <div class="col-xs-12 btn btn-default ">
       <span class="glyphicon glyphicon-wrench" aria-hidden="true" ></span>
      </div>
      <% end %>
      <br>
      <br>
      <h4>投稿<%= @post_images.count %>件</h4>
       <%= render 'follow_form' %>
       <%= render 'stats' %>
     </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-offset-2">
     <%= form_for(@post_image, url: post_images_path) do |f| %>
     <% if @post_image.errors.any? %>
     <div id="error_explanation">
     <h2><%= @post_image.errors.count %>件のエラーが発生しました。</h2>
     <ul>
      <% @post_image.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    </div>
      <% end %>
       <div class="row">
        <div class="col-xs-4">
         <%= f.attachment_field :images_images, multiple: true %>
        </div>
       </div>
       <hr>
       <div class="row">
        <div class="col-sm-12">
         <%= f.text_field :title, class: "form-control", id:"title", placeholder:"タイトル", warp: "hard" %>
        </div>
       </div>
       <hr>
       <div class="row">
        <div class="col-sm-12">
         <%= f.text_area :body, class: "form-control", rows:"3", placeholder:"コメントここに" %>
        </div>
       </div>
       <hr>
       <div class="row">
        <div class="col-sm-12">
         <%= f.submit "送信", class: "btn btn-primary col-xs-12" %>
      <% end %>
        </div>
       </div>
   </div>
  </div>
 </div>
</div>

app/views/post_images/show.html.erb
<%= render 'template/header' %>
<div class="media-area2">
 <div class="container">
  <div class="row">
   <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="circle">
     <h2>User info</h2>
      <table class="table">
       <tbody>
        <div class="image">
         <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class: "img-circle" %>
        </div>
        <br>
	<tr>
         <th>name</th>
	 <th><%= @user.name %></th>
        </tr>
       </tbody>
      </table>
      <%= link_to edit_user_path(@user.id) do %>
       <div class="col-xs-12 btn btn-default ">
        <span class="glyphicon glyphicon-wrench" aria-hidden="true" ></span>
       </div>
      <% end %>
      <br>
      <br>
      <h4>投稿<%= @post_images.count %>件</h4>
      <%= render 'follow_form' %>
      <%= render 'stats' %>
     </div>
    </div>
    <div class="col-xs-12 col-md-offset-2 col-md-7">
     <div class="slider">
      <% @post_image.images.each do |image| %>
      <%= attachment_image_tag image, :image, size: "500x500", class: "sm-image" %>
      <% end %>
     </div>
    <div class="box">
     <h3><%= @post_image.title %></h3>
     <h3><%= @post_image.body %></h3>
     <h4 class="space"><%= @post_image.user.name %></h4>
     <% if @post_image.favorited_by?(current_user) %>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
       <h7><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      <%= @post_image.favorites.count %> いいね</h7>
     <% end %>
      <% else %>
       <%= link_to post_image_favorites_path(@post_image), method: :post do %></h4>
       <i class="fa fa-heart-o" aria-hidden="true"></i>
       <%= @post_image.favorites.count %> いいね
      <% end %>
     <% end %>
     <% if @post_image.user == current_user %>
      <h4><%= link_to "編集", edit_post_image_path(@post_image.id) %>
      <%= link_to "削除", post_image_path(@post_image), method: :delete, "data-confirm" => "本当に削除しますか？" %></h4>
     <% end %>
     <h4>コメント<%= @post_image.post_comments.count %>件</h4>
      <div class="image2"><%= attachment_image_tag @post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60", class: "img-circle profile-thumb" %></div>
       <br>
      </div>
       <br>
      <div class="box2">
       <% if @post_comments.count == 0 %>
        <h4>コメントはまだありません</h4>
       <% else %>
        <% @post_comments.each do |post_comment| %>
         <div><%= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle" %></div>
          <h3><%= link_to post_comment.user.name, user_path(post_comment.user.id) %></h3>
          <h4><%= post_comment.created_at.strftime('%y/%m/%d') %></h4>
          <h4><%= post_comment.comment %></h4>
          <% if current_user == post_comment.user %>
          <h4><%= link_to "削除", post_image_post_comment_path(@post_image.id, post_comment.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <% end %>
         <hr>
        <% end %>
        <%= paginate @post_comments, class: "pagenate" %>
       <% end %>
         </div>
         <div class="box2">
          <%= form_for [@post_image, @post_comment] do |f| %>
          <%= f.text_field :comment, class: "form-control", placeholder: "コメントをここに" %>
          <hr>
          <%= f.submit "送信する", class: "btn btn-success col-xs-12 p-3 mb-2 bg-warning text-white" %>
          <% end %>
         </div>
	 <br>
	 <br>
	 <br>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/post_images/show_follow.html.erb
<%= render 'template/header' %>
<div class="media-area">
 <div class="container">
  <div class="row">
   <div class="col-xs-6">
    <% if @user.followings.count == 0 %>
     <h2>該当なし</h2>
    <% else %>
     <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th>ProfileImage</th>
        <th>name</th>
        <th>詳細</th>
       </tr>
      </thead>
      <tbody>
       <% @user.followings.each do |user| %>        　　　　　　　　　　　　　　
        <tr>
         <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60", class: "img-circle pull-left profile-thumb" %></td>
         <td><%= user.name %></td>
         <td><%= link_to "詳細", user_path(user) %></td>
        </tr>
       <% end %>
      </tbody>
     </table>
    <% end %>
   </div> 
  </div>
 </div>
</div>

app/views/post_images/show_follower.html.erb
<%= render 'template/header' %>
<div class="media-area">
 <div class="container">
  <div class="row">
   <div class="col-xs-7">
    <% if @user.followers.count == 0 %>
     <h2>フォロワーはいません</h2>
    <% else %>
     <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th>ProfileImage</th>
	<th>name</th>
	<th>詳細</th>
       </tr>
      </thead>
      <tbody>
       <% @user.followers.each do |user| %>
        <tr>
         <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60", class: "img-circle pull-left profile-thumb" %></td>
         <td><%= user.name %></td>
         <td><%= link_to '詳細', user_path(user) %></td>
        </tr>
       <% end %>
      </tbody>
     </table>
    <% end %>
   </div>
  </div>
 </div>
</div>

app/views/root/top.html.erb
<%= render 'template/header' %>
<div class="media-area">
 <div class="container">
  <div class="row">
   <h1 class="time">
    <SCRIPT language="JavaScript">
     t = setInterval("DspClk()", 500);
    </SCRIPT>
    <FORM name="ClkForm">
     <INPUT type="text" name="Input">
    </FORM>
   </h1>
 	 <h1 class= "title">Welcome to<i class= "fas fa-portrait"></i>Portfolio !!</h1>
   <h4 class="title2">In  <i class= "fas fa-portrait"></i>Portfolio</h4>
   <div class="box5">
    <div class="circle1"><span><p><%= link_to "Home", top_path, class: "glyphicon glyphicon-home home fa-2x" %></p></span></div>
    <div class="circle2"><span><p1><%= link_to "Log in", new_user_session_path, class: "nav-list-item glyphicon glyphicon-log-in fa-2x" %></p1></span></div>
    <div class="circle3"><span><p2><%= link_to "Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit fa-2x" %></p2></span></div>
    <div class="circle4"><span><p3><%= link_to "Sample App", root_index_path, class: "far fa-user" %></p3></span></div>
   </div>
  </div>
 </div>
</div>

app/views/users/_follow.html.erb
<div class="btn">
  <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <%= f.hidden_field :following_id %>
  <i class="fa fa-user-plus"><%= f.submit "フォローする", class: "btn-twitter-follow" %></i>
  <% end %>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<h4>
 <div class="follow">
  <%= link_to "#{@user.followings.count}人をフォロー中", following_user_path(@user) %>
   <br>
   <br>
  <%= link_to "フォロワー#{@user.followers.count}人", followers_user_path(@user) %>
 </div>
</h4>

app/views/users/_unfollow.html.erb
<div class="btn">
 <%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
 <%= f.submit "フォロー中", class: "btn btn-large btn-primary follow-btn", method: :delete, "data-confirm" => "#{@user.name}さんのフォローをやめますか？" %>
 <% end %>
</div>

app/views/users/index.html.erb
<%= render 'template/header' %>
<div class="media-area2">
 <div class="container">
  <div class="row">
   <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="circle">
     <h2>User info</h2>	     
      <table class="table">
       <tbody>
        <div class="image">
         <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class: "img-circle" %>
        </div>
	<br>
        <tr>
         <th>name</th>
         <th><%= @user.name %></th>
        </tr>
       </tbody>
      </table> 
       <%= link_to edit_user_path(@user.id) do %>
        <div class="col-xs-12 btn btn-default ">
         <span class="glyphicon glyphicon-wrench" aria-hidden="true" ></span>
        </div>
       <% end %>
       <br>
       <br>
       <h4>投稿<%= @post_images.count %>件</h4>
       <%= render 'follow_form' %>
       <%= render 'stats' %>
    </div>
   </div>
   <div class="col-xs-12 col-md-offset-2 col-md-7">
    <% provide(:title, 'All users') %>
    <h1>All users</h1>
    <h2>user search</h2>
    <%= form_tag(users_path, :method => 'get' ) do %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Search', :name => nil %>
    <% end %>
     <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th>profile image</th>
        <th>name</th>
       <tr>
      </thead>
      <tbody>
       <ul class="users">
        <% @users.each do |user| %>
         <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60", class: "img-circle pull-left profile-thumb" %></td>
          <td><%= link_to user.name, user_path(user.id) %></td>
         </tr>
        <% end %>
        <h4><%= paginate @users, class: "pagenate" %></h4>
       </ul>
      </tbody>
     </table>
    </div>
   </div>
  </div>
 </div>

app/views/users/show.html.erb
<%= render 'template/header' %>
<div class="media-area2">
 <div class="container">
  <div class="row">
   <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="circle">
     <h2>User info</h2>
      <table class="table">
       <tbody>
        <div class="image"><%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class: "img-circle" %>
        </div>
         <br>
          <tr>
           <th>name</th>
           <th><%= @user.name %></th>
          </tr>
       </tbody>
      </table>
      <% if current_user != @user %>
       <% else %>
       <%= link_to edit_user_path(@user.id) do %>
       <div class="col-xs-12 btn btn-default ">
        <span class="glyphicon glyphicon-wrench" aria-hidden="true" ></span>
       </div>
       <% end %>
      <% end %>
      <br>
      <br>
      <h4>投稿<%= @post_images.count %>件</h4>
      <%= render 'follow_form' %>
      <%= render 'stats' %>
     </div>
    </div>
     <div class="col-xs-12 col-md-offset-2 col-md-7 ">
     <% if @post_images.count == 0 %>
      <h1>まだ投稿はありません</h1>
      <% else %>
       <% @post_images.each do |post_image| %>
        <div class="slider">
       <% post_image.images.each do |image| %>
       <%= attachment_image_tag image, :image, size: "500x500", class: "sm-image" %>
      <% end %>
        </div>
       <div class="box">
        <h3>
         <%= link_to post_image_path(post_image.id) do %>
         <%= post_image.title %>
         <% end %>
        </h3>
        <h3><%= post_image.body %></h3>
        <h4 class="space"><%= post_image.user.name %></h4>
        <h4><%= link_to "コメント#{post_image.post_comments.count}件", post_image_path(post_image.id) %></h4>
        <br>
       </div>
       <hr>
     <% end %>
     <h4><%= paginate @post_images, class: "pagenate" %></h4>
         <% end %>
   </div>
  </div>
 </div>
</div>